### ISSUE TITLE
Boost asio coredump with highload when breaking client connection

### ISSUE THREAD

**Issue by testillano** [testillano/h2agent#6]
**Describe the bug**
sigsegv fault
To dump the core, open c limits and set the desired core pattern path, for example:
$> ulimit -c unlimited
$>  echo "/tmp/cores/core.%e-%p-%t-%h" | sudo tee -a /proc/sys/kernel/core_pattern

**To Reproduce**
The h2agent must be executed before, so build it and launch with warning traces:
$> build_type=Debug ./build.sh --auto
$> build/Debug/bin/h2agent --verbose

Launch a load over the EC (engineering capacity) and wait for Hermes to finish and close the connection.
For example in a 8-vcpu core machine:
$> cd st/hermes
$> H2AGENT__RESPONSE_DELAY_MS=0 HERMES__RPS=25000 HERMES__DURATION=10 ./start.sh 

**Expected behavior**
When closing, a segmentation fault appears.
Probably linked to timeouts.

```
warning: core file may not match specified executable file.
[New LWP 7478]
[New LWP 7474]
[New LWP 7477]
[New LWP 7471]
[New LWP 7475]
[New LWP 7473]
[New LWP 7472]
[New LWP 7479]
[New LWP 7476]
Core was generated by `./h2agent.debug --verbose'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004c94db in nghttp2_session_recv (session=<optimized out>) at nghttp2_session.c:3283
3283    nghttp2_session.c: No such file or directory.
[Current thread is 1 (LWP 7478)]
(gdb) bt
#0  0x00000000004c94db in nghttp2_session_recv (session=<optimized out>) at nghttp2_session.c:3283
#1  0x0000000000000001 in ?? ()
#2  0x00007f59f7e3f760 in ?? ()
#3  0x00007f59f7e3f760 in ?? ()
#4  0x00007f59f7d493c0 in ?? ()
#5  0x00000000004cf3a5 in nghttp2_http_on_header (session=
    0x718aeb <std::num_get<wchar_t, std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::_M_extract_int<unsigned long long>(std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t> >, std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t> >, std::ios_base&, std::_Ios_Iostate&, unsigned long long&) const+1169>, 
    stream=0x717098 <std::num_get<wchar_t, std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::do_get(std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t> >, std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t> >, std::ios_base&, std::_Ios_Iostate&, bool&) const+554>, frame=0x7f59f7d489f0, nv=0x7f59f7d48640, trailer=-136766664) at nghttp2_http.c:246
#6  0x0000000000000000 in ?? ()
```

**Comment by testillano** [comment]
Partially fixed here [0].
Http2comm bugfix [1].

[0] https://github.com/testillano/h2agent/commit/e4b1f627cb5e3c0feab70ab0a7bf75b12e659448
[1] https://github.com/testillano/http2comm/issues/14
